name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simplebank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # Use 1.22 or whatever your local Go version is

      - name: Set environment variables
        run: |
          echo "DB_SOURCE=postgresql://root:secret@localhost:5432/simplebank?sslmode=disable" >> $GITHUB_ENV

      - name: Install dependencies
        run: go mod tidy

      - name: Run migrations
        run: make migrateup

      - name: Run tests
        run: make test
